stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: img_fiware-postgres_v11.3:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 172.30.76.49:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: Create secret and config map
  steps:
  - applyYamlConfig:
      path: ./secret.yaml
  - applyYamlConfig:
      path: ./postgres-configmap.yaml
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./statefulset-master.yaml
  - applyYamlConfig:
      path: ./service.yaml
  - applyYamlConfig:
      path: ./statefulset-replica.yaml
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        apt-get install sshpass
        sshpass -p password ssh -tt -o StrictHostKeyChecking=no newuser@192.168.100.178 ./check_pod_status.sh p-kpggk-pipeline postgres
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |
        apt-get update
        echo Y | apt-get install npm
        npm -v
        sleep 300
        npm install -g newman
        newman run ./Postgres.postman_collection.json
  when:
    branch: {}
    event: {}
timeout: 60
notification: {}
