stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: img_fiware-postgres_v11.3:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: csp2-centos-1:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
- name: Create secret and config map
  steps:
  - applyYamlConfig:
      path: ./secret.yaml
  - applyYamlConfig:
      path: ./postgres-configmap.yaml
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./statefulset-master.yaml
  - applyYamlConfig:
      path: ./service.yaml
  - applyYamlConfig:
      path: ./statefulset-replica.yaml
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        apt-get install sshpass
        sshpass -p password ssh -tt -o StrictHostKeyChecking=no newuser@192.168.100.178 ./check_pod_status.sh p-kpggk-pipeline postgres
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |
        apt-get update
        echo Y | apt-get install npm
        npm -v
        npm install -g newman
        newman run http://192.168.100.178/csp_containerizationandautomation/postgres/raw/master/Postgres.postman_collection.json
  when:
    branch: {}
    event: {}
timeout: 60
notification: {}
