stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: IMG_fiware-postgres_v11.3:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
- name: Create secret and config map
  steps:
  - applyYamlConfig:
      path: ./secret.yaml
  - applyYamlConfig:
      path: ./postgres-configmap.yaml
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./statefulset-master.yaml
  - applyYamlConfig:
      path: ./service.yaml
  - applyYamlConfig:
      path: ./statefulset-replica.yaml
timeout: 60
notification: {}